In [1]:
import pandas as pd
import numpy as np

# Pandas. Dataframes. Part 1.

1. Напишите программу `Pandas`, которая создает массив данных `Dataframe` из следующей структуры.

Пример данных: `{'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}`

Ожидаемый выход:

| X | Y | Z |
|---|---|---|
| 0 | 78 | 84 | 86 |
| 1 | 85 | 94 | 97 |
| 2 | 96 | 89 | 96 |
| 3 | 80 | 83 | 72 |
| 4 | 86 | 86 | 83 |


In [3]:
df = pd.DataFrame(data={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
df

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Напишите программу `Pandas`, которая создает и отображает `DataFrame` из словаря с указанными индексами `labels`.

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:
| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|


In [4]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3. Напишите программу `Pandas`, которая отображает основную информацию о созданном `Dataframe` (`summary`)

Образец исходных данных:
```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:
```
Summary of the basic information about this DataFrame and its data:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
.... dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None
```


In [5]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Напишите программу `Pandas`, которая отображает 3  первых строки созданного `DataFrame`

Образец исходных данных:
```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:
```
First three rows of the data frame:
```

| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|c|2|Katherine|yes|16.5|

In [6]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

5. Напишите программу `Pandas`, которая отображает столбцы 'name' и 'score' из созданного `DataFrame`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:
| |name|score|
|-|-|-|
|a|Anastasia|12.5|
|b|Dima|9.0|
|...|...|...|
|i|Kevin|8.0|
|j|Jonas|19.0|

In [7]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[['name', 'score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

6.  Напишите программу `Pandas`, которая выбирает из созданного `Dataframe` только указанные строки и столбцы.

Строки: `1, 3, 5, 6`

Столбцы: `score`, `qualify`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:

| |score|qualify|
|-|-|-|
|b| 9.0| no|
|d| NaN| no|
|f| 20.0| yes|
|g| 14.5| yes|


In [8]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df.loc[['b', 'd', 'f', 'g'], ['score', 'qualify']]

score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes



7. Напишите программу `Pandas`, которая выбирает те строки, в которых количество попыток (`attempts`) больше чем 2
Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:

| |name| score| attempts| qualify|
|-|-|-|-|-|
|b| Dima| 9.0| 3| no|
|d| James| NaN| 3| no|
|f| Michael| 20.0| 3| yes|




In [9]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[df['attempts'] > 2 ]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

8. Напишите программу `Pandas`, которая считает количество строк и количество столбцов в указанном `Dataframe`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:
```
Количество строк: 10
Количество столбцов: 4
```



In [10]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
print("Количество строк: ", df.shape[0])
print("Количество строк: ", df.shape[1])

Количество строк:  10
Количество строк:  4


9. Напишите программу `Pandas`, которая выбирает строки в которых отсутствует значение `score` (значение равно `NaN`)

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:

| |attempts| name| qualify| score|
|-|-|-|-|-|
|d| 3| James| no| NaN|
|h| 1| Laura| no| NaN|




In [11]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[df['score'].isnull()]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

10. Напишите программу `Pandas`, которая выбирает строки в которых значение `score` находится на отрезке `[15, 20]` (включительно)

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:

| |attempts| name| qualify| score|
|-|-|-|-|-|
|c| 2| Katherine| yes| 16.5|
|f| 3| Michael| yes| 20.0|
|j| 1| Jonas| yes| 19.0|



In [4]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[(df['score'] >= 15) & (df['score'] <= 20)]

a    False
b    False
c     True
d    False
e    False
f     True
g    False
h    False
i    False
j     True
Name: score, dtype: bool

11. Напишите программу `Pandas`, которая выбирает строки в которых количество попыток `attempts` меньше, чем `2`, а `score` больше чем `15`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
Ожидаемый результат:

| |name| score| attempts| qualify|
|-|-|-|-|-|
|j| Jonas| 19.0| 1| yes|




In [13]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df[(df['attempts'] < 2) & (df['score'] > 15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

12.  Напишите программу `Pandas`, которая изменяет значение `score` в строке `d` на `11.5`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:

| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|d| 3| James| no| 11.5|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|


In [14]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df.loc['d', 'score'] = 11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

13. Напишите программу `Pandas`, которая вычисляет суммарное количество всех попыток (`attempts`) для всех студентов.

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:
```
Суммарное количество попыток для всех студентов:
19
```



In [15]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df['attempts'].sum()

19

14. Напишите программу `Pandas`, которая  вычисляет среднее значение `score` для всех студентов в `Dataframe`

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:
```
Среднее значение score для всех студентов:
13.5625
```


In [16]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df['score'].mean()

13.5625

15. Напишите программу `Pandas`, которая присоединяет строку `k` с указанными значениями в `Dataframe`, выведите полученный результат, затем удалите добавленную строку и выведите исходные данные

Образец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Новая строка:
```
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"
```

Ожидаемый результат:
```
Добавление данных:
```
| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|
|k|1|Suresh |yes| 15.5|

```
Удаление данных:
```

| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|



In [17]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
print(df)
print('\n---------------------------------------\n')

new = {'name' : "Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes", 'label': "k"}
df.loc['k'] = new
print(df)

print('\n---------------------------------------\n')
df = df.drop('k')
print(df)


        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

---------------------------------------

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

---------------------------------------

        name  score  attempts qualify
a  A

16. Напишите программу `Pandas`, которая сортирует `Dataframe` сначала по столбцу `name` в порядке возрастания, а затем по столбцу `score` в порядке убывания

бразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:

```Исходные данные:```
| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|

```Отсортированные данные:```
| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|yes|12.5|
|b|3|Dima|no|9.0|
|...|...|...|...|...|
|i|2|Kevin|no|8.0|
|j|1|Jonas|yes|19.0|

In [18]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df = df.sort_values(by=['name', 'score'], ascending=[True, False])
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James    NaN         3      no
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
i      Kevin    8.0         2      no
h      Laura    NaN         1      no
g    Matthew   14.5         1     yes
f    Michael   20.0         3     yes

17.  Напишите программу `Pandas`, которая заменяет значения `yes` и `no` в столбце `qualify` на `True` и `False`, соответсвенно.


бразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:

| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|True|12.5|
|b|3|Dima|False|9.0|
|...|...|...|...|...|
|i|2|Kevin|False|8.0|
|j|1|Jonas|True|19.0|




In [19]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
df

name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

18. Напишите программу `Pandas`, которая заменяет имя 'James' на 'Suresh' в столбце `name` указанного `DataFrame`


Оразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:


| |attempts|name|qualify|score|
|-|-|-|-|-|
|a|1|Anastasia|True|12.5|
|b|3|Dima|False|9.0|
|...|...|...|...|...|
|i|2|Kevin|False|8.0|
|j|1|Jonas|True|19.0|




In [20]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df['name'] = df['name'].replace('James', 'Suresh')
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

19.  Напишите программу `Pandas`, которая удаляет столбцец `attempts` из указанного `Dataframe`


Оразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:


| |name|qualify|score|
|-|-|-|-|
|a|Anastasia|True|12.5|
|b|Dima|False|9.0|
|...|...|...|...|
|i|Kevin|False|8.0|
|j|Jonas|True|19.0|

In [21]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df.drop('attempts', axis=1, inplace=True)
df

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

20.  Напишите программу `Pandas`, которая добавляет новый столбец `color` в указанный `Dataframe`. (Цвета указать при добавлении по желанию)


Оразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```



Ожидаемый результат:


| |attempts|name|qualify|score|color|
|-|-|-|-|-|-|
|a|1|Anastasia|True|12.5|Blue|
|b|3|Dima|False|9.0|Red|
|...|...|...|...|...|...|
|i|2|Kevin|False|8.0|Green|
|j|1|Jonas|True|19.0|Red|



In [22]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df['color'] = ['red'] * 10
df

name  score  attempts qualify color
a  Anastasia   12.5         1     yes   red
b       Dima    9.0         3      no   red
c  Katherine   16.5         2     yes   red
d      James    NaN         3      no   red
e      Emily    9.0         2      no   red
f    Michael   20.0         3     yes   red
g    Matthew   14.5         1     yes   red
h      Laura    NaN         1      no   red
i      Kevin    8.0         2      no   red
j      Jonas   19.0         1     yes   red

21. Напишите программу `Pandas`, которая итерирует по строкам в `Dataframe` и выводит их на экран.
Образец исходных данных:
```
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
```
Ожидаемый результат:

```
Anastasia 12.5
Dima 9.0
Katherine 16.5
```



In [23]:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
df = pd.DataFrame(data=exam_data)

for _, row in df.iterrows():
    print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Katherine 16.5


22.  Напишите программу `Pandas`, которая получает список ис строки заголовка `Dataframe`

Оразец исходных данных:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

Ожидаемый результат:
```['attempts', 'name', 'qualify', 'score']```


In [24]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data=exam_data, index=labels)
df.columns

Index(['name', 'score', 'attempts', 'qualify'], dtype='object')

23. Напишите программу `Pandas`, которая переименовывает столбцы указанного `Dataframe`

Оразец исходных данных:

| |col1 |col2| col3|
|-|-|-|-|
|0| 1| 4| 7|
|1| 2| 5| 8|
|2| 3| 6| 9|

Ожидаемый результат:

| |Column1| Column2| Column3|
|-|-|-|-|
|0| 1| 4| 7|
|1| 2| 5| 8|
|2| 3| 6| 9|



In [25]:
data = {'col1': [1, 2, 4],
        'col2': [4, 5, 8],
        'col3': [7, 8, 9]}

df = pd.DataFrame(data=data)
print(df)
print('\n---------------------------------------\n')

df.columns = ['column1', 'column2', 'column3']
print(df)


   col1  col2  col3
0     1     4     7
1     2     5     8
2     4     8     9

---------------------------------------

   column1  column2  column3
0        1        4        7
1        2        5        8
2        4        8        9


24. Напишите программу `Pandas`, которая выбирает строки `Dataframe` по условию на значение в определенном столбце

Пример входных данных:

||col1| col2| col3|
|-|-|-|-|
|0| 1| 4| 7|
|1| 4| 5| 8|
|2| 3| 6| 9|
|3| 4| 7| 0|
|4| 5| 8| 1|

Ожидаемый результат:

Строки в которых значение в `col1` == 4:

||col1| col2| col3|
|-|-|-|-|
|1| 4| 5| 8|
|3| 4| 7| 0|



In [26]:
data = {'col1': [1, 4, 3, 4, 5],
        'col2': [4, 5, 6, 7, 8],
        'col3': [7, 8, 9, 0, 1],
        }
df = pd.DataFrame(data=data)
df[df['col1'] == 4]

col1  col2  col3
1     4     5     8
3     4     7     0

25.  Напишите программу `Pandas`, которая изменяет порядок столбцов в `Dataframe`

Пример входных данных:

||col1| col2| col3|
|-|-|-|-|
|0| 1| 4| 7|
|1| 4| 5| 8|
|2| 3| 6| 9|
|3| 4| 7| 0|
|4| 5| 8| 1|

Ожидаемый результат:

||col3| col2| col1|
|-|-|-|-|
|0| 7| 4| 1|
|1| 8| 5| 4|
|2| 9| 6| 3|
|3| 0| 7| 4|
|4| 1| 8| 5|


In [27]:
data = {'col1': [1, 4, 3, 4, 5],
        'col2': [4, 5, 6, 7, 8],
        'col3': [7, 8, 9, 0, 1],
        }
df = pd.DataFrame(data=data)
df = df[['col3', 'col2', 'col1']]
df

col3  col2  col1
0     7     4     1
1     8     5     4
2     9     6     3
3     0     7     4
4     1     8     5